### ISSUE TITLE
Get package ready for MELPA

### ISSUE THREAD

**Issue by plexus** [plexus/a.el#1]
The MELPA people can be picky about things. It'd be great to get some eyes on the package *before* submitting to make sure the process goes smoothly.

- [x] correctly add dependency versions (including minimum version of Emacs. I'm guessing 25+ will be required)
- [x] run the linter to make sure all the magic formatting is there
- [x] submit PR to MELPA

**Comment by dotemacs** [comment]
See https://github.com/melpa/melpa/pull/4830

**Comment by plexus** [comment]
I went through the docstrings with checkdoc, and made sure they all mention their variables. It still complains over a few things that I simply don't agree with.

- "contains should be in the imperative case" - uh no it shouldn't 
- "arguments are mentioned out of order" - seriously? maybe leave the human language things to humans tyvm
- "longer than 80 columns" - hate to break it to you but teletypes are dead. I wouldn't mind going through them and hitting M-q everywhere, but that also doesn't work because "the first line has to be a complete sentence"

Shall I just leave these, or do I make a commit to make checkdoc happy, and then revert it once the melpa package is up?

Thanks a lot for the help by the way, really appreciated!

**Comment by dotemacs** [comment]
> "contains should be in the imperative case" - uh no it shouldn't

I saw that too. But didn't know what you wanted to do with it.
I agree with you here.


> "longer than 80 columns" - hate to break it to you but teletypes are dead. I wouldn't mind going through them and hitting M-q everywhere, but that also doesn't work because "the first line has to be a complete sentence"

I'm a strong believer of keeping the text under 80 columns. 

Just look at the `a.el` file in GitHub via the browser. You can read all of the code, but you have to scroll left->right, just to read the comment.

What do you want to do about the comment Steve Purcell made about the suffixes to the functions being `-?` instead of `-p` ?

**Comment by plexus** [comment]
I guess I'll check my ego at the door for a moment and do whatever it takes to make checkdoc happy, even if it includes butchering grammar 🙈

> What do you want to do about the comment Steve Purcell made about the suffixes to the functions being -? instead of -p ?

I'm going to look at them case by case and add a `-p` alias where it makes sense.

**Comment by plexus** [comment]
I am no longer going to pursue this, instead a.el is now hosted on its own ELPA repository. (see the README).

Leaving this issue here for reference. If anyone wants to keep trying to get this into ELPA they are welcome to do so.

**Comment by alphapapa** [comment]
I'm glad it worked out in the end, this library looks very nice!

**Comment by plexus** [comment]
The package is in MELPA. Thanks everyone for helping out!
