### ISSUE TITLE
Simple set function?

### ISSUE THREAD

**Issue by alphapapa** [plexus/a.el#5]
Hi,

Thanks for making `a`, it is very nice and is coming in handy for a little library I'm working on.

Could we have a simple setting function, like `a-set`?  Something that could be used like:

```el
(setq mylist (a-set mylist :one 1))
```
`a-merge` is useful, but having to make a list to pass to it seems like overkill when I only want to update one value.  And unfortunately, `setf` doesn't work with `a-get`, so `a-merge` seems like the only way to update values using `a`.  I'd like to avoid having to do:
```el
(let ((mylist (a-list :num 1)))
  (setf (cdr (assoc :num mylist)) 2)
  mylist)
```

This seems to work, although I don't know if it's how you'd want to do it:
```el
(defun a-set (coll k v)
  (if (assoc k coll)
      (progn
        (setf (cdr (assoc k coll)) v)
        coll)
    (cons (cons k v) coll)))
```

Thanks.

**Comment by plexus** [comment]
Are you looking for `a-assoc`?

```
(a-assoc (a-list :foo :bar) :baz 123)
;;=> ((:baz . 123) (:foo . :bar))
```

**Comment by alphapapa** [comment]
Apparently so.  So I guess the problem is the name of `a-assoc`.  ;)  I expected `a-assoc` to do what `assoc` does, i.e. return the value of the key in the collection, not set the value of the key in the collection.  Maybe we could have an alias of `a-assoc` to `a-set`?  It would make it much easier to discover.

Thanks.

**Comment by plexus** [comment]
This library copies the API of clojure, where assoc does exactly this.

**Comment by alphapapa** [comment]
I see.  That makes it a bit confusing where it conflicts (in name) with standard elisp functions.  But I appreciate the consistency of the API compared to the elisp ones.  An `a-set` alias would help bridge the gap.

**Comment by alphapapa** [comment]
`a-put` would also work, although I suppose `set` is more lispy.
