### ISSUE TITLE
Destructive setter?

### ISSUE THREAD

**Issue by alphapapa** [plexus/a.el#6]
Hi,

Would you consider adding a destructive version of `a-assoc`?  e.g. asoc.el has `asoc-put!`, which avoids the need to combine with `setq` when appropriate.

Thanks.

**Comment by plexus** [comment]
Hi @alphapapa,

Destructive functions are out of scope for a.el. Other libraries already do these, including the `map` library which comes with current Emacs `(map-put MAP KEY VALUE)`.

This library is a very deliberate mimicking of the Clojure API, which also doesn't have a `put!` (at least not that kind of `put!`).

The only destructive operation I could consider adding would be `a-swap!`, analogous to Clojure/ClojureScript `swap!`.

``` el
(setq state (a-list :counter 5))

(a-swap! state 'a-update :counter '1+)

state ;;=> ((:counter . 6))
```
