### ISSUE TITLE
Nested getter

### ISSUE THREAD

**Issue by alphapapa** [plexus/a.el#7]
Hi again,

I recently had this PR merged into ht.el for a nested hash-table getter: https://github.com/Wilfred/ht.el/issues/17  What do you think about doing one for `a-get`?  Like:

```el
(defmacro a-get* (&rest keys)
  (cl-labels ((rec (keys)
                   `(a-get ,(if (and (consp (cdr keys))
                                     (cddr keys))
                                (rec (cdr keys))
                              (cadr keys))
                           ,(car keys))))
    (rec (nreverse keys))))

(let ((alphabets (a-list "Greek" (a-list 1 (a-list 'letter "α"
                                                   'name "alpha")
                                         2 (a-list 'letter "β"
                                                   'name "beta"))
                         "English" (a-list 1 (a-list 'letter "a"
                                                     'name "A")
                                           2 (a-list 'letter "b"
                                                     'name "B")))))
  (a-get* alphabets "Greek" 1 'letter))  ; => "α"
```

Thanks.

**Comment by plexus** [comment]
Would `a-get-in` serve your purpose?

``` el
(let ((alphabets (a-list "Greek" (a-list 1 (a-list 'letter "α"
                                                   'name "alpha")
                                         2 (a-list 'letter "β"
                                                   'name "beta"))
                         "English" (a-list 1 (a-list 'letter "a"
                                                     'name "A")
                                           2 (a-list 'letter "b"
                                                     'name "B")))))
  (a-get-in alphabets ["Greek" 1 letter])) ;;=> "α"
```

**Comment by alphapapa** [comment]
Sorry, I should have mentioned that.  I saw that function, but having to put the keys in a vector feels awkward.  I'd like to avoid that.

**Comment by alphapapa** [comment]
Hi again.  Would you consider adding the macro?  It could be rewritten more simply using something like `dolist` instead of the recursive function.  I ask because I could really use it right now, and I already have it defined in my project, but I'll be cleaning it up for submission to MELPA, so I can't have macro called `a-get*` in it.  And it seems a shame to define a macro for this purpose in my project when it seems like it belongs here.  :)

**Comment by plexus** [comment]
@volrath do you have an opinion on this? My first instinct is to say no because `a.el` is meant to be a direct translation of clojure equivalents, and there is no `get*` in Clojure.

On the other hand vectors in elisp are automatically quoted, making them less useful for this kind of thing. You could switch to `(a-get-in m (list ...))` but I agree that would get tedious.

``` lisp
;; clojure
[(+ 1 1)] ;;=> [2]
;;elisp
[(+ 1 1)] ;;=> [(+ 1 1)]
```

**Comment by volrath** [comment]
I agree with avoiding the name `a-get*` in order to maintain close to Clojure's API.

Having said that, the difference of behavior between Clojure and Elisp vectors makes it impossible to keep this direct translation in a coherent way, imo.

I'd opt for making `a-get-in` take the path as a list, or take it as `&rest` arguments, and then document this decision.

**Comment by plexus** [comment]
The problem with that is that `get-in` already has an optional trailing argument (`not-found`)

```
clojure.core/get-in
([m ks] [m ks not-found])
  Returns the value in a nested associative structure,
  where ks is a sequence of keys. Returns nil if the key
  is not present, or the not-found value if supplied.
```

**Comment by plexus** [comment]
Hi @alphapapa,

I'm willing to add this as `a-get-in*`. I'm not a fan of overloading `a-get-in` because lists can also be keys.

I think the implementation can be as simple as

``` emacs-lisp
(defun a-get-in* (m &rest ks)
  (apply #'a-get-in (list m ks)))
```

Does that look good?

**Comment by alphapapa** [comment]
@plexus I'd prefer `a-get*`, because one of my goals is to reduce verbosity, e.g. I could just put the macro in my project and call it something like `matrix-client--aget`, but then I've got extra `matrix-client--` all over the place.  Of course, this is the way things are with Elisp and MELPA.

So, `-in` is only 3 more characters, so no big deal, right?  But then why not leave them out in the first place?  This is a really useful library, and it seems a shame to limit it to what Clojure does.

Anyway, it's your library.  Thanks.

**Comment by alphapapa** [comment]
Thank you!
